- hosts: locust
  become: True
  tasks:
  - name: Update the machine
    command: sudo apt update -y

  - name: Installing dependencies
    command: sudo apt install python3 python3-pip -y

  - name: Installing locust
    command:  sudo -H pip3 install locust

  - name: Installing faker
    command: sudo -H pip3 install faker
